// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ResearchApi.Migrations
{
    [DbContext(typeof(Mycontext))]
    [Migration("20231214102131_eersteresearch")]
    partial class eersteresearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Researchdata", b =>
                {
                    b.Property<int>("Ocode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ocode"));

                    b.Property<string>("Link_Research")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_Research")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("compensation")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Ocode");

                    b.ToTable("Research");
                });
#pragma warning restore 612, 618
        }
    }
}
