name: Test React and .NET Projects

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js dependencies and run React tests
        run: |
          cd path/to/your/react/project
          npm install
          npm test

      - name: Build and run API Docker containers
        uses: docker/build-push-action@v2
        with:
          context: ChatApi
          file: ChatApi/Dockerfile
          push: false # Zet op true als je de image wilt pushen naar een Docker registry

          # Voeg hier andere Docker build-stappen toe voor andere API's op dezelfde manier

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0' # Pas de versie aan indien nodig

      - name: Test APIs
        run: |
          cd Test.ChatApi
          dotnet test &

          # Voeg hier andere API-testprojecten toe op dezelfde manier

      - name: Wait for API tests to complete
        run: wait

  merge-allowed:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'

    steps:
      - name: Check test status
        if: ${{ needs.test.result == 'success' }}
        run: echo "Tests passed. You can merge this pull request."
      
      - name: Check test status
        if: ${{ needs.test.result != 'success' }}
        run: echo "Tests failed. Cannot merge this pull request."
