name: Test React and .NET Projects

on:
  pull_request:
    branches:
      - main
      - 'development*'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Set up working directory
        run: cd any-portal-frontend
                
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        
      - name: Checkout code
        uses: actions/checkout@v2

      

      - name: Build and run ChatApi Docker containers

        uses: docker/build-push-action@v2
        with:
          context: ChatApi
          file: ChatApi/Dockerfile
          push: false # Zet op true als je de image wilt pushen naar een Docker registry

      - name: Build and run LoginApi Docker containers
        uses: docker/build-push-action@v2
        with:
            context: LoginApi
            file: LoginApi/Dockerfile
            push: false  
            
      - name: Build and run MedicalApi Docker containers
        uses: docker/build-push-action@v2
        with:
            context: MedicalApi
            file: MedicalApi/Dockerfile
            push: false 

      - name: Build and run ResearchApi Docker containers
        uses: docker/build-push-action@v2
        with:
            context: ResearchApi
            file: ResearchApi/Dockerfile
            push: false 

      - name: Build and run UserApi Docker containers
        uses: docker/build-push-action@v2
        with:
            context: UserApi
            file: UserApi/Dockerfile
            push: false 

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Run Test ChatAPi
        run: 
          cd Test.ChatApi &&
          dotnet test 

      - name: Run Test LoginApi
        run: 
          cd Test.LoginApi &&
          dotnet test 

      - name: Run Test MedicalApi
        run: 
           cd Test.MedicalApi &&
          dotnet test 

      - name: Run Test ResearchApi
        run: 
          cd Test.ResearchApi &&
          dotnet test 

      - name: Run Test UserApi
        run: 
          cd Test.UserApi &&
          dotnet test 

      

  merge-allowed:
    needs: test
    runs-on: ubuntu-latest
    if: always()  # Deze regel zorgt ervoor dat de job altijd wordt uitgevoerd

    steps:
      - name: Check test is succes
        if: ${{ needs.test.result == 'success' }}
        run: echo "Tests passed. You can merge this pull request."
      
      - name: Check test is failed
        if: ${{ needs.test.result != 'success' }}
        run: echo "Tests failed. Cannot merge this pull request."
