name: Test React and .NET Projects

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run API Docker containers
        uses: docker/build-push-action@v2
        with:
          context: ChatApi
          file: ChatApi/Dockerfile
          push: false # Zet op true als je de image wilt pushen naar een Docker registry

          # Voeg hier andere Docker build-stappen toe voor andere API's op dezelfde manier

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0' # Pas de versie aan indien nodig

      - name: Test APIs
        run: |
          cd Test.ChatApi
          dotnet test &

          # Voeg hier andere API-testprojecten toe op dezelfde manier

      - name: Wait for API tests to complete
        run: wait

  merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check test results and merge if successful
        if: ${{ job.status == 'success' }}
        uses: pullreminders/merge-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
