name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          cd React/my-react-app
          npm run test
          export CYPRESS_EXIT_CODE=$?

      - name: Build and deploy if tests pass
        if: ${{ env.CYPRESS_EXIT_CODE == 0 }}
        run: |
          npm run build
          npm install -g gh-pages
          gh-pages -d build -b main -m "Deploy React app to GitHub Pages"
