name: Cypress Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd React/my-react-app
          npm install

      - name: Run Cypress tests
        run: |
          cd React/my-react-app
          npm run test
      
      - name: Build and deploy if tests pass
        if: ${{ success() }}
        run: |
          cd React/my-react-app
          npm run build
          npm install -g gh-pages
          gh-pages -d build -b main -m "Deploy React app to GitHub Pages"
